"""add_raw_text_to_resumes

Revision ID: 3d38516328b7
Revises: 
Create Date: 2026-07-06 05:46:00.964000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d38516328b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'raw_text')
    # ### end Alembic commands ###
